version: '3.8'

services:
  auto-voice-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: auto-voice:latest
    container_name: auto_voice_container
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - PYTHONPATH=/app/src
      # Removed FLASK_APP since we're not using 'flask run'
      - FLASK_ENV=production
    volumes:
      - ./data:/app/data
      - ./config:/app/config
      - ./logs:/app/logs
    ports:
      - "5000:5000"
      - "8080:8080"  # For WebSocket if needed
    networks:
      - auto-voice-net
    restart: unless-stopped
    command: ["python3", "main.py"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  # Optional: Separate service for training if needed
  auto-voice-training:
    build:
      context: .
      dockerfile: Dockerfile
    image: auto-voice-training:latest
    container_name: auto_voice_training
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - PYTHONPATH=/app/src
    volumes:
      - ./data:/app/data
      - ./config:/app/config
      - ./scripts:/app/scripts
    networks:
      - auto-voice-net
    depends_on:
      - auto-voice-app
    profiles:
      - training
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  auto-voice-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16