"""Create voice_profiles and training_samples tables

Revision ID: 90be4b85c4bb
Revises: 
Create Date: 2026-01-24 21:23:05.098204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90be4b85c4bb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('samples_count', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('model_path', sa.Text(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_voice_profiles_user_created', 'voice_profiles', ['user_id', 'created'], unique=False)
    op.create_index(op.f('ix_voice_profiles_user_id'), 'voice_profiles', ['user_id'], unique=False)
    op.create_table('training_samples',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('audio_path', sa.Text(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('sample_rate', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('processed', sa.Integer(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['voice_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_training_samples_profile_created', 'training_samples', ['profile_id', 'created'], unique=False)
    op.create_index(op.f('ix_training_samples_profile_id'), 'training_samples', ['profile_id'], unique=False)
    op.create_index('ix_training_samples_profile_processed', 'training_samples', ['profile_id', 'processed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_training_samples_profile_processed', table_name='training_samples')
    op.drop_index(op.f('ix_training_samples_profile_id'), table_name='training_samples')
    op.drop_index('ix_training_samples_profile_created', table_name='training_samples')
    op.drop_table('training_samples')
    op.drop_index(op.f('ix_voice_profiles_user_id'), table_name='voice_profiles')
    op.drop_index('ix_voice_profiles_user_created', table_name='voice_profiles')
    op.drop_table('voice_profiles')
    # ### end Alembic commands ###
