#!/bin/bash
# AutoVoice Setup for NVIDIA Jetson AGX Thor
# Generated by Ralph Loop orchestration
# Platform: Thor (sm_110), JetPack R38.4.0, CUDA 13.0

set -e

echo "=== AutoVoice Jetson Thor Setup ==="
echo "Platform: NVIDIA Jetson AGX Thor (sm_110)"
echo "JetPack: R38.4.0"
echo "CUDA: 13.0"
echo ""

# Check if running on Thor
if ! nvidia-smi &>/dev/null; then
    echo "ERROR: NVIDIA GPU not detected. This script is for Jetson Thor."
    exit 1
fi

# Get script directory
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

# Conda setup
CONDA_BASE="${CONDA_BASE:-$HOME/anaconda3}"
if [ ! -d "$CONDA_BASE" ]; then
    CONDA_BASE="$HOME/miniconda3"
fi

if [ ! -f "$CONDA_BASE/etc/profile.d/conda.sh" ]; then
    echo "ERROR: Conda not found at $CONDA_BASE"
    echo "Please install Anaconda or Miniconda first."
    exit 1
fi

source "$CONDA_BASE/etc/profile.d/conda.sh"

ENV_NAME="autovoice-thor"

# Check if environment exists
if conda env list | grep -q "^${ENV_NAME} "; then
    echo "Environment $ENV_NAME already exists."
    read -p "Recreate it? (y/N) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        conda env remove -n $ENV_NAME -y
    else
        echo "Using existing environment."
        conda activate $ENV_NAME
    fi
fi

# Create environment if it doesn't exist
if ! conda env list | grep -q "^${ENV_NAME} "; then
    echo "Creating conda environment: $ENV_NAME"
    conda create -n $ENV_NAME python=3.12 -y
fi

conda activate $ENV_NAME

echo ""
echo "=== Installing PyTorch for CUDA 13.0 ==="
# Install PyTorch nightly with CUDA 13.0 support
pip install --pre torch torchvision torchaudio \
    --index-url https://download.pytorch.org/whl/nightly/cu130

# Verify PyTorch CUDA
echo ""
echo "=== Verifying PyTorch CUDA ==="
python -c "
import torch
print(f'PyTorch version: {torch.__version__}')
print(f'CUDA available: {torch.cuda.is_available()}')
if torch.cuda.is_available():
    print(f'CUDA version: {torch.version.cuda}')
    print(f'GPU: {torch.cuda.get_device_name(0)}')
    # Test tensor operations
    x = torch.randn(1000, 1000).cuda()
    y = torch.mm(x, x)
    print(f'GPU tensor test: PASSED')
else:
    print('WARNING: CUDA not available!')
    exit(1)
"

echo ""
echo "=== Installing Core Dependencies ==="
pip install -r "$PROJECT_DIR/requirements-jetson.txt"

echo ""
echo "=== Installing Additional ML Dependencies ==="
pip install transformers webrtcvad noisereduce resemblyzer
pip install torchcrepe praat-parselmouth

echo ""
echo "=== Installing Demucs (Source Separation) ==="
pip install --no-deps demucs

echo ""
echo "=== Installing Development Tools ==="
pip install pytest pytest-cov tensorboard

echo ""
echo "=== Installing Package in Development Mode ==="
cd "$PROJECT_DIR"
export TORCH_CUDA_ARCH_LIST="11.0"
pip install -e .

echo ""
echo "=== Verifying Installation ==="
python -c "
import torch
print('✓ PyTorch:', torch.__version__)

from auto_voice.web.app import create_app
print('✓ Flask app factory')

from auto_voice.audio import AudioProcessor
print('✓ Audio processor')

try:
    from auto_voice.inference import VoiceSynthesizer
    print('✓ Voice synthesizer')
except ImportError as e:
    print(f'⚠ Voice synthesizer (optional): {e}')

print('')
print('=== AutoVoice Installation Complete ===')
print(f'Environment: {\"$ENV_NAME\"}')
print(f'Python: {\"$(python --version)\"}')
print(f'PyTorch: {torch.__version__}')
print(f'CUDA: {torch.version.cuda}')
"

echo ""
echo "=== Setup Complete ==="
echo ""
echo "To activate the environment:"
echo "  conda activate $ENV_NAME"
echo ""
echo "To start the server:"
echo "  cd $PROJECT_DIR"
echo "  python main.py --host 0.0.0.0 --port 5000"
echo ""
echo "To run tests:"
echo "  pytest tests/ -v --ignore=tests/gpu"
echo ""
